services:
  # Ambiente de Homologação
  - type: web
    name: api-angar-homologacao
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: staging
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 3600
      - key: KEY_ANGAR
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: WHATSAPP_API_URL
        value: https://graph.facebook.com/v18.0
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_TEMPLATE_NAME
        value: proposta_emprestimo_confirmacao
    healthCheckPath: /health

  # Ambiente de Produção
  - type: web
    name: api-angar-producao
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 3600
      - key: KEY_ANGAR
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: WHATSAPP_API_URL
        value: https://graph.facebook.com/v18.0
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_TEMPLATE_NAME
        value: proposta_emprestimo_confirmacao
    healthCheckPath: /health
